name: Mocka

settings:
  DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
  TARGETED_DEVICE_FAMILY: 3
  # https://forums.swift.org/t/swift-packages-in-multiple-targets-results-in-this-will-result-in-duplication-of-library-code-errors/34892/36
  DISABLE_DIAMOND_PROBLEM_DIAGNOSTIC: true

options:
  minimumXcodeGenVersion: "2.11.0"
  bundleIdPrefix: com.wisemotions
  developmentLanguage: en
  indentWidth: 2
  xcodeVersion: 12.4
  deploymentTarget:
    macOS: "11.0"
  generateEmptyDirectories: true

packages:
  Vapor:
    url: https://github.com/vapor/vapor
    from: 4.0.0
    
targets:
  MockaApp:
    type: application
    platform: macOS
    attributes:
      ProvisioningStyle: Automatic
    settings:
      PRODUCT_NAME: "Mocka"
      PRODUCT_MODULE_NAME: "MockaApp"
    sources:
      - path: Sources/App
    dependencies:
      - target: MockaServer
    scheme:
      testTargets:
        - MockaAppTests
      gatherCoverageData: true
      randomExecutionOrder: true
      customArchiveName: Mocka
      revealArchiveInOrganizer: false
    info:
      path: Sources/App/Resources/Info.plist
      properties:
        CFBundleDevelopmentRegion: "$(DEVELOPMENT_LANGUAGE)"
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        LSMinimumSystemVersion: "$(MACOSX_DEPLOYMENT_TARGET)"

  MockaAppTests:
    type: bundle.unit-test
    platform: macOS
    settings:
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Mocka.app/Contents/MacOS/Mocka"
    sources:
      - path: Tests/AppTests
    dependencies:
      - target: MockaApp
    info:
      path: Tests/AppTests/Resources/Info.plist
      properties:
        CFBundleDevelopmentRegion: "$(DEVELOPMENT_LANGUAGE)"
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"

  MockaServer:
    type: framework
    platform: macOS
    sources:
      - path: Sources/Server
    dependencies:
      - package: Vapor
    scheme:
      testTargets:
        - MockaServerTests
      gatherCoverageData: true
      randomExecutionOrder: true
      customArchiveName: Server
      revealArchiveInOrganizer: false
    info:
      path: Sources/Server/Resources/Info.plist
      properties:
        CFBundleDevelopmentRegion: "$(DEVELOPMENT_LANGUAGE)"
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"

  MockaServerTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests/ServerTests
    dependencies:
      - target: MockaServer
      - package: Vapor
        product: XCTVapor
    info:
      path: Tests/ServerTests/Resources/Info.plist
      properties:
        CFBundleDevelopmentRegion: "$(DEVELOPMENT_LANGUAGE)"
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
