name: Format Code

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the following branch.
  push:
    branches:
    - main
    - develop
    - release/*
  pull_request:
    branches:
    - '*'

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called "format".
  format:
    # The type of runner that the job will run on.
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - uses: actions/checkout@v2

      # Setup the project by using the setup.sh file.
      - name: Setup Project & Format All Code
        run: ./setup.sh format

      # Commit all the formatted source files.
      - name: Git Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v4.9.2
        with:
          commit_message: Format code
